# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './src/SavingsProjection.SPA/SavingsProjection.SPA.csproj'
    arguments: '-o "$(Pipeline.Workspace)/output" -c "Release"'
    modifyOutputPath: false

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/output'
    artifact: 'BlazorFrontend'
    publishLocation: 'pipeline'
