name: Build Backend

on:
  push:
    branches: [ master ]
    paths:
    - 'src/Savings.API/**'
  
  
  workflow_dispatch:

jobs:
  Build-Backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build .NET Backend
      run: dotnet publish Savings.API.csproj -o "output" -c "Release"
      working-directory: ./src/Savings.API

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: savings-backend
        path: ./src/Savings.API/output/*
        if-no-files-found: error
        retention-days: 90
