name: Build Frontend

on:
  push:
    branches: [ master ]
    paths:
    - 'src/Savings.SPA/**'
    
  workflow_dispatch:

jobs:
  Build-Frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build .NET Frontend
      run: dotnet publish Savings.SPA.csproj -o "output" -c "Release"
      working-directory: ./src/Savings.SPA

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: savings-frontend
        path: ./src/Savings.SPA/output/*
        if-no-files-found: error
        retention-days: 90
