name: Deploy Frontend on Azure

on:
  workflow_dispatch:
   inputs:
        appservice_suffix:
          description: "AppService Suffix"
          required: true
          default: "DEFAULT"

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Download Backend Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-backend.yml
          name: savings-projection-frontend
          branch: master
          path: ./deploy

      - name: Calculate dynamic secret name with suffix
        run: |
          echo "APP_SERVICE_NAME_VARIABLE=APPSERVICENAME_FE_${{github.event.inputs.appservice_suffix }}" >> $GITHUB_ENV
          echo "API_KEY_VARIABLE=APPSERVICE_CONFIG_APIKEY_${{ github.event.inputs.appservice_suffix }}" >> $GITHUB_ENV
          echo "IDENTITY_AUTHORITY_VARIABLE=APPSERVICE_CONFIG_IDENTITY_AUTHORITY_${{ github.event.inputs.appservice_suffix }}" >> $GITHUB_ENV
          echo "IDENTITY_CLIENT_ID_VARIABLE=APPSERVICE_FE_CONFIG_IDENTITY_CLIENT_ID_${{ github.event.inputs.appservice_suffix }}" >> $GITHUB_ENV
          echo "IDENTITY_DEFAULT_SCOPE_VARIABLE=APPSERVICE_FE_CONFIG_IDEFAULT_SCOPE_${{ github.event.inputs.appservice_suffix }}" >> $GITHUB_ENV
      - name: Config Settings Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'deploy/appsettings.json,deploy/appsettings.Development.json,deploy/appsettings.Production.json'
        env:
          SavingProjectionApiServiceUrl: ${{ secrets[env.API_KEY_VARIABLE] }}
          ApiKey: ${{ secrets[env.API_KEY_VARIABLE] }}
          AuthenticationToUse: 'AzureAD'
          AzureAd.Authority: ${{ secrets[env.IDENTITY_AUTHORITY_VARIABLE] }}
          AzureAd.ClientId: ${{ secrets[env.IDENTITY_CLIENT_ID_VARIABLE] }}
          AzureAd.DefaultScope: ${{ secrets[env.IDENTITY_DEFAULT_SCOPE_VARIABLE] }}

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name:    ${{ secrets[env.APP_SERVICE_NAME_VARIABLE] }}
          package: ./deploy
